<?php

use CodeIgniter\Router\RouteCollection;

/**
 * @var RouteCollection $routes
 */
$routes->get('auth/login', 'Auth::login');
$routes->get('auth/google', 'Auth::google');
$routes->get('auth/google/link', 'Auth::linkGoogle', ['filter' => 'auth']);
$routes->get('auth/google/callback', 'Auth::googleCallback');
$routes->post('auth/request-otp', 'Auth::requestOtp', ['filter' => 'rateLimit']);
$routes->get('auth/register', 'Auth::register');
$routes->get('auth/otp', 'Auth::otp');
$routes->post('auth/otp', 'Auth::verifyOtp');
$routes->post('auth/otp/resend', 'Auth::resendOtp', ['filter' => 'rateLimit']);
$routes->get('auth/forgot-password', 'Auth::forgotPassword');
$routes->get('auth/logout', 'Auth::logout', ['filter' => 'auth']);
$routes->get('/', 'HomeController::index', ['filter' => 'auth']);
$routes->get('beranda', 'HomeController::index', ['filter' => 'auth']);
$routes->post('konteks-aktif', 'ActiveContextController::update', ['filter' => 'auth']);
$routes->get('catat', 'TransactionController::index', ['filter' => 'auth']);
$routes->get('catat/masuk', 'TransactionController::masuk', ['filter' => 'auth']);
$routes->post('catat/masuk', 'TransactionController::simpanMasuk', ['filter' => 'auth']);
$routes->get('catat/keluar', 'TransactionController::keluar', ['filter' => 'auth']);
$routes->get('catat/keluar/biaya', 'TransactionController::biaya', ['filter' => 'auth']);
$routes->post('catat/keluar/biaya', 'TransactionController::simpanBiaya', ['filter' => 'auth']);
$routes->get('catat/keluar/honor-gaji', 'TransactionController::honor', ['filter' => 'auth']);
$routes->post('catat/keluar/honor-gaji', 'TransactionController::simpanHonor', ['filter' => 'auth']);
$routes->get('catat/keluar/pindah-dana', 'TransactionController::pindahDana', ['filter' => 'auth']);
$routes->post('catat/keluar/pindah-dana', 'TransactionController::simpanPindahDana', ['filter' => 'auth']);
$routes->post('catat/hapus/(:num)', 'TransactionController::hapus/$1', ['filter' => 'auth']);
$routes->post('ai/scan-bill', 'AiController::scanBill', ['filter' => 'auth']);
$routes->get('rekap', 'ReportController::index', ['filter' => 'auth']);
$routes->get('pengaturan', 'SettingsController::pengaturan', ['filter' => 'auth']);
$routes->get('pengaturan/profil-lembaga', 'SettingsController::profilLembaga', ['filter' => 'auth']);
$routes->post('pengaturan/profil-lembaga', 'SettingsController::simpanProfilLembaga', ['filter' => 'auth']);
$routes->get('pengaturan/profil-lembaga/edit', 'SettingsController::editProfilLembaga', ['filter' => 'auth']);
$routes->get('pengaturan/unit-program', 'SettingsController::masterUnitProgram', ['filter' => 'auth']);
$routes->get('pengaturan/unit-program/tambah', 'SettingsController::tambahUnitProgram', ['filter' => 'auth']);
$routes->post('pengaturan/unit-program', 'SettingsController::simpanUnitProgram', ['filter' => 'auth']);
$routes->get('pengaturan/unit-program/(:segment)/edit', 'SettingsController::editUnitProgram/$1', ['filter' => 'auth']);
$routes->post('pengaturan/unit-program/(:segment)', 'SettingsController::updateUnitProgram/$1', ['filter' => 'auth']);
$routes->post('pengaturan/unit-program/(:segment)/hapus', 'SettingsController::hapusUnitProgram/$1', ['filter' => 'auth']);
$routes->get('pengaturan/kegiatan', 'SettingsController::masterKegiatan', ['filter' => 'auth']);
$routes->get('pengaturan/kegiatan/tambah', 'SettingsController::tambahKegiatan', ['filter' => 'auth']);
$routes->post('pengaturan/kegiatan', 'SettingsController::simpanKegiatan', ['filter' => 'auth']);
$routes->get('pengaturan/kegiatan/(:segment)/edit', 'SettingsController::editKegiatan/$1', ['filter' => 'auth']);
$routes->post('pengaturan/kegiatan/(:segment)', 'SettingsController::updateKegiatan/$1', ['filter' => 'auth']);
$routes->post('pengaturan/kegiatan/(:segment)/hapus', 'SettingsController::hapusKegiatan/$1', ['filter' => 'auth']);
$routes->get('pengaturan/rekening-dompet', 'SettingsController::masterRekeningDompet', ['filter' => 'auth']);
$routes->get('pengaturan/rekening-dompet/tambah', 'SettingsController::tambahRekeningDompet', ['filter' => 'auth']);
$routes->post('pengaturan/rekening-dompet', 'SettingsController::simpanRekeningDompet', ['filter' => 'auth']);
$routes->get('pengaturan/rekening-dompet/(:segment)/edit', 'SettingsController::editRekeningDompet/$1', ['filter' => 'auth']);
$routes->post('pengaturan/rekening-dompet/(:segment)', 'SettingsController::updateRekeningDompet/$1', ['filter' => 'auth']);
$routes->post('pengaturan/rekening-dompet/(:segment)/hapus', 'SettingsController::hapusRekeningDompet/$1', ['filter' => 'auth']);
$routes->get('pengaturan/kategori-biaya', 'SettingsController::masterKategoriBiaya', ['filter' => 'auth']);
$routes->get('pengaturan/kategori-biaya/tambah', 'SettingsController::tambahKategoriBiaya', ['filter' => 'auth']);
$routes->post('pengaturan/kategori-biaya', 'SettingsController::simpanKategoriBiaya', ['filter' => 'auth']);
$routes->get('pengaturan/kategori-biaya/(:segment)/edit', 'SettingsController::editKategoriBiaya/$1', ['filter' => 'auth']);
$routes->post('pengaturan/kategori-biaya/(:segment)', 'SettingsController::updateKategoriBiaya/$1', ['filter' => 'auth']);
$routes->post('pengaturan/kategori-biaya/(:segment)/hapus', 'SettingsController::hapusKategoriBiaya/$1', ['filter' => 'auth']);
$routes->get('pengaturan/pos-laporan', 'SettingsController::masterPosLaporan', ['filter' => 'auth']);
$routes->get('pengaturan/pos-laporan/tambah', 'SettingsController::tambahPosLaporan', ['filter' => 'auth']);
$routes->post('pengaturan/pos-laporan', 'SettingsController::simpanPosLaporan', ['filter' => 'auth']);
$routes->get('pengaturan/pos-laporan/(:segment)/edit', 'SettingsController::editPosLaporan/$1', ['filter' => 'auth']);
$routes->post('pengaturan/pos-laporan/(:segment)', 'SettingsController::updatePosLaporan/$1', ['filter' => 'auth']);
$routes->post('pengaturan/pos-laporan/(:segment)/hapus', 'SettingsController::hapusPosLaporan/$1', ['filter' => 'auth']);
$routes->get('pengaturan/tahun-buku', 'SettingsController::masterTahunBuku', ['filter' => 'auth']);
$routes->get('pengaturan/tahun-buku/tambah', 'SettingsController::tambahTahunBuku', ['filter' => 'auth']);
$routes->post('pengaturan/tahun-buku', 'SettingsController::simpanTahunBuku', ['filter' => 'auth']);
$routes->get('pengaturan/tahun-buku/(:segment)/edit', 'SettingsController::editTahunBuku/$1', ['filter' => 'auth']);
$routes->post('pengaturan/tahun-buku/(:segment)', 'SettingsController::updateTahunBuku/$1', ['filter' => 'auth']);
$routes->post('pengaturan/tahun-buku/(:segment)/hapus', 'SettingsController::hapusTahunBuku/$1', ['filter' => 'auth']);
$routes->get('pengaturan/saldo-awal', 'SettingsController::masterSaldoAwal', ['filter' => 'auth']);
$routes->get('pengaturan/saldo-awal/tambah', 'SettingsController::tambahSaldoAwal', ['filter' => 'auth']);
$routes->post('pengaturan/saldo-awal', 'SettingsController::simpanSaldoAwal', ['filter' => 'auth']);
$routes->get('pengaturan/saldo-awal/(:segment)/edit', 'SettingsController::editSaldoAwal/$1', ['filter' => 'auth']);
$routes->post('pengaturan/saldo-awal/(:segment)', 'SettingsController::updateSaldoAwal/$1', ['filter' => 'auth']);
$routes->post('pengaturan/saldo-awal/(:segment)/hapus', 'SettingsController::hapusSaldoAwal/$1', ['filter' => 'auth']);
$routes->get('pengaturan/penerima', 'SettingsController::masterPenerima', ['filter' => 'auth']);
$routes->get('pengaturan/penerima/tambah', 'SettingsController::tambahPenerima', ['filter' => 'auth']);
$routes->post('pengaturan/penerima', 'SettingsController::simpanPenerima', ['filter' => 'auth']);
$routes->get('pengaturan/penerima/(:segment)/edit', 'SettingsController::editPenerima/$1', ['filter' => 'auth']);
$routes->post('pengaturan/penerima/(:segment)', 'SettingsController::updatePenerima/$1', ['filter' => 'auth']);
$routes->post('pengaturan/penerima/(:segment)/hapus', 'SettingsController::hapusPenerima/$1', ['filter' => 'auth']);
$routes->get('transaksi/(:segment)', 'TransactionController::detail/$1', ['filter' => 'auth']);
$routes->get('transaksi/(:segment)/edit', 'TransactionController::edit/$1', ['filter' => 'auth']);
$routes->post('transaksi/(:segment)', 'TransactionController::update/$1', ['filter' => 'auth']);
$routes->get('rekening/(:segment)', 'ReportController::rekening/$1', ['filter' => 'auth']);
$routes->get('penerima/(:segment)', 'ReportController::penerima/$1', ['filter' => 'auth']);
$routes->get('unit/(:segment)', 'ReportController::unit/$1', ['filter' => 'auth']);
$routes->get('unit/(:segment)/bagikan', 'ReportController::bagikanUnit/$1', ['filter' => 'auth']);
$routes->post('unit/(:segment)/bagikan', 'ReportController::simpanBagikanUnit/$1', ['filter' => 'auth']);
$routes->get('kegiatan/(:segment)', 'ReportController::kegiatan/$1', ['filter' => 'auth']);
$routes->post('kegiatan/(:segment)/proyek', 'ReportController::updateProyekKegiatan/$1', ['filter' => 'auth']);
$routes->post('kegiatan/(:segment)/kantong', 'ReportController::simpanKantongKegiatan/$1', ['filter' => 'auth']);
$routes->get('kegiatan/(:segment)/kantong/(:segment)', 'ReportController::kantongKegiatan/$1/$2', ['filter' => 'auth']);
$routes->post('kegiatan/(:segment)/kantong/(:segment)', 'ReportController::updateKantongKegiatan/$1/$2', ['filter' => 'auth']);
$routes->post('kegiatan/(:segment)/kantong/(:segment)/nonaktif', 'ReportController::nonaktifkanKantongKegiatan/$1/$2', ['filter' => 'auth']);
$routes->get('laporan/unit/(:segment)', 'ReportController::laporanUnitPublik/$1');
$routes->post('laporan/unit/(:segment)/unlock', 'ReportController::bukaLaporanUnitPublik/$1');
