<?php

use CodeIgniter\Router\RouteCollection;

/**
 * @var RouteCollection $routes
 */
$routes->get('auth/login', 'Auth::login');
$routes->post('auth/request-otp', 'Auth::requestOtp', ['filter' => 'rateLimit']);
$routes->get('auth/register', 'Auth::register');
$routes->get('auth/otp', 'Auth::otp');
$routes->post('auth/otp', 'Auth::verifyOtp');
$routes->post('auth/otp/resend', 'Auth::resendOtp', ['filter' => 'rateLimit']);
$routes->get('auth/forgot-password', 'Auth::forgotPassword');
$routes->get('auth/logout', 'Auth::logout', ['filter' => 'auth']);
$routes->get('/', 'Arus::home', ['filter' => 'auth']);
$routes->get('beranda', 'Arus::home', ['filter' => 'auth']);
$routes->get('catat', 'Arus::catat', ['filter' => 'auth']);
$routes->get('catat/masuk', 'Arus::catatMasuk', ['filter' => 'auth']);
$routes->post('catat/masuk', 'Arus::simpanMasuk', ['filter' => 'auth']);
$routes->get('catat/keluar', 'Arus::catatKeluar', ['filter' => 'auth']);
$routes->get('catat/keluar/biaya', 'Arus::catatBiaya', ['filter' => 'auth']);
$routes->post('catat/keluar/biaya', 'Arus::simpanBiaya', ['filter' => 'auth']);
$routes->get('catat/keluar/honor-gaji', 'Arus::catatHonorGaji', ['filter' => 'auth']);
$routes->post('catat/keluar/honor-gaji', 'Arus::simpanHonorGaji', ['filter' => 'auth']);
$routes->get('catat/keluar/pindah-dana', 'Arus::catatPindahDana', ['filter' => 'auth']);
$routes->post('catat/keluar/pindah-dana', 'Arus::simpanPindahDana', ['filter' => 'auth']);
$routes->get('rekap', 'Arus::rekap', ['filter' => 'auth']);
$routes->get('pengaturan', 'Arus::pengaturan', ['filter' => 'auth']);
$routes->get('pengaturan/profil-lembaga', 'Arus::profilLembaga', ['filter' => 'auth']);
$routes->post('pengaturan/profil-lembaga', 'Arus::simpanProfilLembaga', ['filter' => 'auth']);
$routes->get('pengaturan/profil-lembaga/edit', 'Arus::editProfilLembaga', ['filter' => 'auth']);
$routes->get('pengaturan/unit-program', 'Arus::masterUnitProgram', ['filter' => 'auth']);
$routes->get('pengaturan/unit-program/tambah', 'Arus::tambahUnitProgram', ['filter' => 'auth']);
$routes->post('pengaturan/unit-program', 'Arus::simpanUnitProgram', ['filter' => 'auth']);
$routes->get('pengaturan/unit-program/(:segment)/edit', 'Arus::editUnitProgram/$1', ['filter' => 'auth']);
$routes->post('pengaturan/unit-program/(:segment)', 'Arus::updateUnitProgram/$1', ['filter' => 'auth']);
$routes->post('pengaturan/unit-program/(:segment)/hapus', 'Arus::hapusUnitProgram/$1', ['filter' => 'auth']);
$routes->get('pengaturan/kegiatan', 'Arus::masterKegiatan', ['filter' => 'auth']);
$routes->get('pengaturan/kegiatan/tambah', 'Arus::tambahKegiatan', ['filter' => 'auth']);
$routes->post('pengaturan/kegiatan', 'Arus::simpanKegiatan', ['filter' => 'auth']);
$routes->get('pengaturan/kegiatan/(:segment)/edit', 'Arus::editKegiatan/$1', ['filter' => 'auth']);
$routes->post('pengaturan/kegiatan/(:segment)', 'Arus::updateKegiatan/$1', ['filter' => 'auth']);
$routes->post('pengaturan/kegiatan/(:segment)/hapus', 'Arus::hapusKegiatan/$1', ['filter' => 'auth']);
$routes->get('pengaturan/rekening-dompet', 'Arus::masterRekeningDompet', ['filter' => 'auth']);
$routes->get('pengaturan/rekening-dompet/tambah', 'Arus::tambahRekeningDompet', ['filter' => 'auth']);
$routes->post('pengaturan/rekening-dompet', 'Arus::simpanRekeningDompet', ['filter' => 'auth']);
$routes->get('pengaturan/rekening-dompet/(:segment)/edit', 'Arus::editRekeningDompet/$1', ['filter' => 'auth']);
$routes->post('pengaturan/rekening-dompet/(:segment)', 'Arus::updateRekeningDompet/$1', ['filter' => 'auth']);
$routes->post('pengaturan/rekening-dompet/(:segment)/hapus', 'Arus::hapusRekeningDompet/$1', ['filter' => 'auth']);
$routes->get('pengaturan/kategori-biaya', 'Arus::masterKategoriBiaya', ['filter' => 'auth']);
$routes->get('pengaturan/kategori-biaya/tambah', 'Arus::tambahKategoriBiaya', ['filter' => 'auth']);
$routes->post('pengaturan/kategori-biaya', 'Arus::simpanKategoriBiaya', ['filter' => 'auth']);
$routes->get('pengaturan/kategori-biaya/(:segment)/edit', 'Arus::editKategoriBiaya/$1', ['filter' => 'auth']);
$routes->post('pengaturan/kategori-biaya/(:segment)', 'Arus::updateKategoriBiaya/$1', ['filter' => 'auth']);
$routes->post('pengaturan/kategori-biaya/(:segment)/hapus', 'Arus::hapusKategoriBiaya/$1', ['filter' => 'auth']);
$routes->get('pengaturan/pos-laporan', 'Arus::masterPosLaporan', ['filter' => 'auth']);
$routes->get('pengaturan/pos-laporan/tambah', 'Arus::tambahPosLaporan', ['filter' => 'auth']);
$routes->post('pengaturan/pos-laporan', 'Arus::simpanPosLaporan', ['filter' => 'auth']);
$routes->get('pengaturan/pos-laporan/(:segment)/edit', 'Arus::editPosLaporan/$1', ['filter' => 'auth']);
$routes->post('pengaturan/pos-laporan/(:segment)', 'Arus::updatePosLaporan/$1', ['filter' => 'auth']);
$routes->post('pengaturan/pos-laporan/(:segment)/hapus', 'Arus::hapusPosLaporan/$1', ['filter' => 'auth']);
$routes->get('pengaturan/tahun-buku', 'Arus::masterTahunBuku', ['filter' => 'auth']);
$routes->get('pengaturan/tahun-buku/tambah', 'Arus::tambahTahunBuku', ['filter' => 'auth']);
$routes->post('pengaturan/tahun-buku', 'Arus::simpanTahunBuku', ['filter' => 'auth']);
$routes->get('pengaturan/tahun-buku/(:segment)/edit', 'Arus::editTahunBuku/$1', ['filter' => 'auth']);
$routes->post('pengaturan/tahun-buku/(:segment)', 'Arus::updateTahunBuku/$1', ['filter' => 'auth']);
$routes->post('pengaturan/tahun-buku/(:segment)/hapus', 'Arus::hapusTahunBuku/$1', ['filter' => 'auth']);
$routes->get('pengaturan/saldo-awal', 'Arus::masterSaldoAwal', ['filter' => 'auth']);
$routes->get('pengaturan/saldo-awal/tambah', 'Arus::tambahSaldoAwal', ['filter' => 'auth']);
$routes->post('pengaturan/saldo-awal', 'Arus::simpanSaldoAwal', ['filter' => 'auth']);
$routes->get('pengaturan/saldo-awal/(:segment)/edit', 'Arus::editSaldoAwal/$1', ['filter' => 'auth']);
$routes->post('pengaturan/saldo-awal/(:segment)', 'Arus::updateSaldoAwal/$1', ['filter' => 'auth']);
$routes->post('pengaturan/saldo-awal/(:segment)/hapus', 'Arus::hapusSaldoAwal/$1', ['filter' => 'auth']);
$routes->get('pengaturan/penerima', 'Arus::masterPenerima', ['filter' => 'auth']);
$routes->get('pengaturan/penerima/tambah', 'Arus::tambahPenerima', ['filter' => 'auth']);
$routes->post('pengaturan/penerima', 'Arus::simpanPenerima', ['filter' => 'auth']);
$routes->get('pengaturan/penerima/(:segment)/edit', 'Arus::editPenerima/$1', ['filter' => 'auth']);
$routes->post('pengaturan/penerima/(:segment)', 'Arus::updatePenerima/$1', ['filter' => 'auth']);
$routes->post('pengaturan/penerima/(:segment)/hapus', 'Arus::hapusPenerima/$1', ['filter' => 'auth']);
$routes->get('transaksi/(:segment)', 'Arus::transaksi/$1', ['filter' => 'auth']);
$routes->get('transaksi/(:segment)/edit', 'Arus::editTransaksi/$1', ['filter' => 'auth']);
$routes->get('rekening/(:segment)', 'Arus::rekening/$1', ['filter' => 'auth']);
$routes->get('unit/(:segment)', 'Arus::unit/$1', ['filter' => 'auth']);
$routes->get('kegiatan/(:segment)', 'Arus::kegiatan/$1', ['filter' => 'auth']);
